# Ruby/Rails sample project for analyzer verification
source 'https://rubygems.org'

gem 'rails', '~> 7.1.0'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.60', require: false
end

gem 'rake'
